"""Tests for ``dfwb.preprocess.packbuild``: one dataset of a protocol pack, built from an inventory.

``PackDemoBuilder`` is a small synthetic dataset registered through a fake plugin: ten real
identities, two face-swap methods, an official split read from a JSON file in its dataset folder,
an identity carve, an all-test scheme, a benchmark drawn from the official test, and pairs.
The helpers below are shared with the materialize and CLI tests.
"""

from __future__ import annotations

import json
import os
from collections.abc import Sequence
from pathlib import Path
from typing import Any

import pytest
import yaml
from tests.unit.preprocess.inventory._demo import install

from dfwb import __version__
from dfwb.core.errors import ConfigError, ContractError, UnknownKeyError
from dfwb.core.hashing import sha256_text
from dfwb.core.records import (
    BuilderRef,
    DatasetCard,
    InventoryRecord,
    PackProvenance,
    PairRecord,
    VideoRecord,
    read_jsonl,
    read_split_tsv,
    split_sha256,
    write_jsonl,
)
from dfwb.preprocess.inventory.base import BaseBuilder, LabelSpec, SchemeSpec, TaskSpec
from dfwb.preprocess.inventory.runner import build_inventory, get_builder, read_inventory
from dfwb.preprocess.packbuild import (
    BuildResult,
    _notice,
    add_to_pack_yaml,
    assign_scheme,
    build_dataset,
    locate_metadata_root,
)
from dfwb.protocols._yaml import read_card
from dfwb.protocols.lint import lint_pack
from dfwb.protocols.materialization import materialize, needs_official
from dfwb.protocols.rules import BenchmarkSpec, Split, assign_benchmark, local_key

_MODULE = "tests.unit.preprocess.test_packbuild"
PACKDEMO_TARGET = f"{_MODULE}:PackDemoBuilder"
PACK_NAME = "packdemo-pack"
_SPLITS_FILE = "splits.json"
_IDENTITIES = tuple(f"p{i:02d}" for i in range(10))
_OFFICIAL = {"train": _IDENTITIES[:6], "val": _IDENTITIES[6:8], "test": _IDENTITIES[8:]}


class PackDemoBuilder(BaseBuilder):
    """Reals ``originals/<id>``; fakes ``swap_a|swap_b/<target>_<source>``; splits in JSON."""

    dataset_id = "packdemo"
    expected_folder = "PackDemo"
    label_prefix = "PD"
    tasks = (
        TaskSpec("REAL", "Originals", "real", "originals", "original"),
        TaskSpec("FS_A", "Swapper A", "fake", "swap_a", "SwapA"),
        TaskSpec("FS_B", "Swapper B", "fake", "swap_b", "SwapB"),
    )
    metadata_files = (_SPLITS_FILE,)
    labels = {
        "REAL": LabelSpec(binary=0, binary_av=0, multiclass=0, family="real"),
        "FS_A": LabelSpec(binary=1, binary_av=1, multiclass=1, family="face-swap"),
        "FS_B": LabelSpec(binary=1, binary_av=1, multiclass=2, family="face-swap"),
    }
    schemes = {
        "official": SchemeSpec(
            "official", "official", source=_SPLITS_FILE, rationale="the publisher's split"
        ),
        "ident-72-14-14": SchemeSpec("ident-72-14-14", "derived", rationale="identity carve"),
        "all-test": SchemeSpec("all-test", "subset", rationale="every video is test"),
        "benchmark": SchemeSpec("benchmark", "subset", rationale="a small balanced test set"),
    }
    default_scheme = "official"
    benchmark = BenchmarkSpec(k_fake=2)
    pairing_rule = "target-id"
    card_info = {
        "name": "Pack Demo",
        "release": "1",
        "homepage": "https://example.org/packdemo",
        "license": {"spdx": None, "summary": "synthetic test data"},
        "access": "generated by the tests",
        "modalities": ["video"],
        "compressions": None,
        "key_rule": "<task>/<file stem>",
    }

    def record_for_video(
        self, task: TaskSpec, path: Path, relpath: str, compression: str | None
    ) -> InventoryRecord | None:
        stem = path.stem
        if task.kind == "real":
            return self.record(task, stem, relpath, compression, identity=stem, target_id=stem)
        target, _, source = stem.partition("_")
        return self.record(
            task,
            stem,
            relpath,
            compression,
            identity=target,
            target_id=target,
            source_id=source,
            pair_key=target,
        )

    def official_splits(self, root: Path, records: Sequence[InventoryRecord]) -> dict[str, Split]:
        path = root / _SPLITS_FILE
        if not path.is_file():
            raise ConfigError(f"packdemo: {path} is missing", hint="write splits.json")
        listed = json.loads(path.read_text("utf-8"))
        by_identity = {ident: split for split, idents in listed.items() for ident in idents}
        return {r.key: by_identity[r.identity] for r in records if r.identity in by_identity}

    def pair_candidates(self, fake: InventoryRecord) -> str | None:
        return fake.target_id


class PackDemoCarveBuilder(PackDemoBuilder):
    """The same release as a train/test dataset: the official test plus an 80/20 carve of train.

    It publishes no val (its reader drops the val identities), pairs nothing, and cites a paper.
    """

    dataset_id = "packdemo-carve"
    schemes = {
        "official+ident-80-20": SchemeSpec(
            "official+ident-80-20",
            "derived",
            params={"policy": "official-train-test"},
            source=_SPLITS_FILE,
            rationale="the official test, and train carved into train and val",
        ),
        "all-test": SchemeSpec("all-test", "subset", rationale="every video is test"),
    }
    default_scheme = "official+ident-80-20"
    benchmark = None
    pairing_rule = None
    card_info = {
        **PackDemoBuilder.card_info,
        "name": "Pack Demo Carve",
        "homepage": None,
        "paper": {"title": "A Synthetic Release", "venue": "Tests", "year": 2026},
    }

    def official_splits(self, root: Path, records: Sequence[InventoryRecord]) -> dict[str, Split]:
        official = super().official_splits(root, records)
        return {key: split for key, split in official.items() if split != "val"}


class PackDemoValOnlyBuilder(PackDemoBuilder):
    """A release whose publisher labels only its val split (AV-Deepfake1M++ is one): no test."""

    dataset_id = "packdemo-valonly"

    def official_splits(self, root: Path, records: Sequence[InventoryRecord]) -> dict[str, Split]:
        official = super().official_splits(root, records)
        return {key: split for key, split in official.items() if split == "val"}


class PackDemoNoOfficialBuilder(PackDemoBuilder):
    """A release with no publisher's split at all: an identity carve and a benchmark only."""

    dataset_id = "packdemo-noofficial"
    metadata_files = ()
    schemes = {
        "ident-72-14-14": SchemeSpec("ident-72-14-14", "derived", rationale="identity carve"),
        "benchmark": SchemeSpec("benchmark", "subset", rationale="a small balanced test set"),
    }
    default_scheme = "ident-72-14-14"

    def official_splits(self, root: Path, records: Sequence[InventoryRecord]) -> dict[str, Split]:
        raise AssertionError("a dataset without an official scheme never reads one")


def make_packdemo_tree(folder: Path) -> Path:
    """The raw release: 10 reals, 10 fakes per method, and the official split file."""
    for index, identity in enumerate(_IDENTITIES):
        for directory, stem in (
            ("originals", identity),
            ("swap_a", f"{identity}_{_IDENTITIES[(index + 1) % 10]}"),
            ("swap_b", f"{identity}_{_IDENTITIES[(index + 2) % 10]}"),
        ):
            (folder / directory).mkdir(parents=True, exist_ok=True)
            (folder / directory / f"{stem}.mp4").touch()
    (folder / _SPLITS_FILE).write_text(
        json.dumps({split: list(ids) for split, ids in _OFFICIAL.items()}), "utf-8"
    )
    return folder


def make_pack_root(tmp_path: Path) -> Path:
    """An importable, empty pack (``datasets: []``); returns the directory holding pack.yaml."""
    package = tmp_path / "dfwb_packdemo_fixture"
    root = package / "pack"
    root.mkdir(parents=True)
    (package / "__init__.py").write_text("")
    (root / "pack.yaml").write_text(
        "schema_version: 1\nname: packdemo-pack\nversion: 1.0.0\ndatasets: []\n", "utf-8"
    )
    return root


def setup_packdemo(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, *, register_pack: bool = True
) -> dict[str, Path]:
    """Roots, the raw release, a built inventory and an empty registered pack."""
    monkeypatch.chdir(tmp_path)
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "home" / ".config"))
    for name in list(os.environ):
        if name.startswith("DFWB_"):
            monkeypatch.delenv(name)
    raw, work = tmp_path / "raw", tmp_path / "work"
    monkeypatch.setenv("DFWB_DATASETS_ROOT", str(raw))
    monkeypatch.setenv("DFWB_WORK_ROOT", str(work))
    make_packdemo_tree(raw / "PackDemo")
    pack = make_pack_root(tmp_path)
    install(
        monkeypatch,
        {
            "packdemo": (PACKDEMO_TARGET, "Pack Demo", "PackDemo"),
            "packdemo-carve": (f"{_MODULE}:PackDemoCarveBuilder", "Pack Demo Carve", "PackDemo"),
            "packdemo-valonly": (f"{_MODULE}:PackDemoValOnlyBuilder", "Val Only", "PackDemo"),
            "packdemo-noofficial": (
                f"{_MODULE}:PackDemoNoOfficialBuilder",
                "No Official",
                "PackDemo",
            ),
        },
        packs={PACK_NAME: pack} if register_pack else None,
    )
    inventory = build_inventory("packdemo").path
    return {"raw": raw, "work": work, "pack": pack, "inventory": inventory}


@pytest.fixture
def demo(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> dict[str, Path]:
    return setup_packdemo(monkeypatch, tmp_path)


def _files(folder: Path) -> dict[str, bytes]:
    return {
        path.relative_to(folder).as_posix(): path.read_bytes()
        for path in sorted(folder.rglob("*"))
        if path.is_file()
    }


# ---------------------------------------------------------------------------------------------
# build_dataset
# ---------------------------------------------------------------------------------------------


def test_build_dataset_writes_a_lint_clean_dataset(demo):
    out = demo["pack"] / "packdemo"

    result = build_dataset("packdemo", out=out)
    added = add_to_pack_yaml(demo["pack"], "packdemo")

    assert isinstance(result, BuildResult)
    assert result.out == out
    assert (result.n_videos, result.n_pairs) == (30, 20)
    assert set(result.schemes) == {"official", "ident-72-14-14", "all-test", "benchmark"}
    assert added is True
    assert sorted(_files(out)) == [
        "NOTICE.md",
        "PROVENANCE.json",
        "dataset.yaml",
        "labels.yaml",
        "pairs.jsonl.gz",
        "splits/all-test.tsv.gz",
        "splits/benchmark.tsv.gz",
        "splits/ident-72-14-14.tsv.gz",
        "splits/official.tsv.gz",
        "videos.jsonl.gz",
    ]
    issues = lint_pack(demo["pack"])
    assert [i for i in issues if i.severity == "error"] == []
    assert [i.message for i in issues] == ["distribution is undecided"]


def test_build_is_byte_reproducible(demo, tmp_path):
    first = build_dataset("packdemo", out=tmp_path / "a" / "packdemo")
    build_dataset("packdemo", out=tmp_path / "b" / "packdemo")
    # The inventory's row order never matters: the same rows, reversed, give the same bytes.
    rows = read_inventory("packdemo", demo["work"])
    reversed_inventory = tmp_path / "reversed.jsonl"
    write_jsonl(reversed_inventory, list(reversed(rows)))
    build_dataset("packdemo", out=tmp_path / "c" / "packdemo", inventory=reversed_inventory)
    # Rebuilding in place changes nothing either.
    build_dataset("packdemo", out=first.out)

    a = _files(tmp_path / "a" / "packdemo")
    assert a == _files(tmp_path / "b" / "packdemo")
    assert a == _files(tmp_path / "c" / "packdemo")
    assert str(tmp_path) not in "".join(v.decode("utf-8", "replace") for v in a.values())


def test_scheme_card_has_rule_params_counts_and_hash(demo):
    out = demo["pack"] / "packdemo"
    result = build_dataset("packdemo", out=out)

    card = read_card(out)
    assert card.schemes == result.schemes
    assert card.default_scheme == "official"
    assert card.distribution == "undecided"

    official = result.schemes["official"]
    assert (official.kind, official.rule, official.source) == (
        "official",
        "official",
        "splits.json",
    )
    assert official.rationale == "the publisher's split"
    assert official.params == {}
    assert official.counts == {"test": 6, "train": 18, "val": 6}
    for name, scheme in result.schemes.items():
        rows = read_split_tsv(out / "splits" / f"{name}.tsv.gz")
        assert scheme.sha256 == split_sha256(rows)
        assert sum((scheme.counts or {}).values()) == len(rows)

    carve = result.schemes["ident-72-14-14"]
    assert (carve.kind, carve.rule, carve.params) == ("derived", "ident-72-14-14", {})
    assert sum((carve.counts or {}).values()) == 30
    assert result.schemes["all-test"].counts == {"test": 30}

    benchmark = result.schemes["benchmark"]
    assert (benchmark.kind, benchmark.rule) == ("subset", "benchmark")
    assert benchmark.params == {
        "k_fake": 2,
        "strata": [],
        "k_real_cap": None,
        "exclude_tasks": [],
        "seed": 0,
        "task_order": ["REAL", "FS_A", "FS_B"],
        "pool": "official-test",
        "compressions": None,
    }
    assert benchmark.counts == {"test": 4}


def test_benchmark_is_drawn_from_the_official_test(demo):
    out = demo["pack"] / "packdemo"
    build_dataset("packdemo", out=out)

    rows = read_split_tsv(out / "splits" / "benchmark.tsv.gz")
    identities = {local_key(row.key).partition("_")[0] for row in rows}
    assert identities <= set(_OFFICIAL["test"])
    assert sorted(row.key for row in rows if row.key.startswith("REAL/")) == [
        "REAL/p08",
        "REAL/p09",
    ]


def test_videos_labels_pairs_and_provenance(demo):
    out = demo["pack"] / "packdemo"
    build_dataset("packdemo", out=out)

    videos = read_jsonl(out / "videos.jsonl.gz", VideoRecord)
    records = read_inventory("packdemo", demo["work"])
    assert [v.key for v in videos] == [r.key for r in records]
    assert videos[0] == VideoRecord(
        key="FS_A/p00_p01",
        compression=None,
        label_key="PD-FS_A",
        method="SwapA",
        identity="p00",
        source_id="p01",
        target_id="p00",
        pair_key="p00",
        attrs={"task_name": "Swapper A"},
    )

    labels = yaml.safe_load((out / "labels.yaml").read_text("utf-8"))
    assert labels["vocab"]["PD-FS_B"] == {
        "binary": 1,
        "binary_av": 1,
        "family": "face-swap",
        "method": "SwapB",
        "multiclass": 2,
        "task": "FS_B",
    }

    pairs = read_jsonl(out / "pairs.jsonl.gz", PairRecord)
    assert len(pairs) == 20
    assert PairRecord("FS_B/p09_p01", "REAL/p09", "target-id") in pairs

    provenance = PackProvenance.model_validate_json((out / "PROVENANCE.json").read_text("utf-8"))
    listing = "".join(sorted(f"{r.key}\t{r.compression or ''}\t{r.relpath}\n" for r in records))
    assert provenance.builder == {"id": "packdemo", "version": "1"}
    assert provenance.dfwb == __version__
    assert provenance.source_listing_sha256 == sha256_text(listing)
    assert provenance.rules["official"] == {"rule": "official", "params": {}}
    assert provenance.rules["benchmark"]["params"]["pool"] == "official-test"
    assert set(provenance.rules) == {"official", "ident-72-14-14", "all-test", "benchmark"}


def test_notice_names_the_owner_never_media_and_the_pending_terms_review(demo):
    out = demo["pack"] / "packdemo"
    build_dataset("packdemo", out=out)

    notice = (out / "NOTICE.md").read_text("utf-8")
    assert "Pack Demo" in notice
    assert "https://example.org/packdemo" in notice
    assert "generated by the tests" in notice
    assert "never media" in notice.lower()
    assert "terms review pending" in notice.lower()


@pytest.mark.parametrize(
    ("distribution", "notes", "expected"),
    [
        ("list", None, "distribution: list, so these lists may be redistributed."),
        ("recipe", None, "distribution: recipe, so the pack publishes each split's rule"),
        ("list", "Our own data.", "may be redistributed. Our own data."),
    ],
)
def test_the_notice_terms_follow_a_decided_distribution(distribution, notes, expected):
    card = DatasetCard.model_validate(
        {
            "id": "decided",
            "name": "Decided",
            "release": "1",
            "license": {"summary": "ours"},
            "access": "generated by the tests",
            "distribution": distribution,
            "terms": {"notes": notes},
            "modalities": ["video"],
            "key_rule": "<task>/<file stem>",
            "schemes": {"all-test": {"kind": "subset", "sha256": "a" * 64}},
            "default_scheme": "all-test",
        }
    )
    notice = _notice(card)
    assert "pending" not in notice.lower()
    assert "Terms reviewed: dataset.yaml records " in notice
    assert expected in notice


def test_scheme_selection_writes_only_those_schemes(demo):
    out = demo["pack"] / "packdemo"
    build_dataset("packdemo", out=out)

    result = build_dataset("packdemo", out=out, schemes=["official", "all-test"])

    assert set(result.schemes) == {"official", "all-test"}
    assert sorted(p.name for p in (out / "splits").iterdir()) == [
        "all-test.tsv.gz",
        "official.tsv.gz",
    ]
    assert set(read_card(out).schemes) == {"official", "all-test"}


def test_unknown_scheme_is_a_config_error_with_a_suggestion(demo):
    with pytest.raises(UnknownKeyError) as info:
        build_dataset("packdemo", out=demo["pack"] / "packdemo", schemes=["official", "benchmrk"])
    assert "did you mean 'benchmark'" in info.value.message


def test_a_selection_without_the_default_scheme_is_refused(demo):
    with pytest.raises(ConfigError) as info:
        build_dataset("packdemo", out=demo["pack"] / "packdemo", schemes=["all-test"])
    assert "official" in info.value.message
    assert "--scheme official" in info.value.hint


def test_missing_default_inventory_hints_inventory_build(demo):
    (demo["work"] / "packdemo" / "inventory.jsonl").unlink()
    with pytest.raises(ConfigError) as info:
        build_dataset("packdemo", out=demo["pack"] / "packdemo")
    assert info.value.hint == "run: dfwb inventory build packdemo"


def test_missing_inventory_file_is_a_config_error(demo, tmp_path):
    with pytest.raises(ConfigError) as info:
        build_dataset("packdemo", out=demo["pack"] / "packdemo", inventory=tmp_path / "nope.jsonl")
    assert "nope.jsonl" in info.value.message


def test_an_inventory_from_another_builder_is_refused(demo, tmp_path):
    rows = read_inventory("packdemo", demo["work"])
    other = tmp_path / "other.jsonl"
    write_jsonl(
        other,
        [
            InventoryRecord(**{**_as_dict(r), "builder": BuilderRef("demo", "1")}) if i == 3 else r
            for i, r in enumerate(rows)
        ],
    )
    with pytest.raises(ContractError) as info:
        build_dataset("packdemo", out=demo["pack"] / "packdemo", inventory=other)
    assert "demo" in info.value.message
    assert "packdemo" in info.value.message


def test_output_inside_a_datasets_root_is_refused(demo):
    with pytest.raises(ConfigError) as info:
        build_dataset("packdemo", out=demo["raw"] / "PackDemo" / "pack" / "packdemo")
    assert "datasets root" in info.value.message
    assert not (demo["raw"] / "PackDemo" / "pack").exists()


def test_official_rule_without_dataset_dir_hints_location(demo):
    builder = get_builder("packdemo")
    records = read_inventory("packdemo", demo["work"])

    for scheme in ("official", "benchmark"):
        with pytest.raises(ConfigError) as info:
            assign_scheme(builder, scheme, records, dataset_dir=None)
        assert info.value.hint == "locate the dataset folder (see dfwb datasets info packdemo)"

    # The rules that never read the publisher's files need no folder.
    assert len(assign_scheme(builder, "ident-72-14-14", records, dataset_dir=None)) == 30
    assert len(assign_scheme(builder, "all-test", records, dataset_dir=None)) == 30


def test_assign_scheme_reads_the_official_split_from_the_dataset_folder(demo):
    builder = get_builder("packdemo")
    records = read_inventory("packdemo", demo["work"])

    assignment = assign_scheme(builder, "official", records, dataset_dir=demo["raw"] / "PackDemo")

    assert assignment[("REAL/p00", None)] == "train"
    assert assignment[("FS_B/p07_p09", None)] == "val"
    assert assignment[("FS_A/p09_p00", None)] == "test"


def test_assign_scheme_unknown_scheme(demo):
    builder = get_builder("packdemo")
    with pytest.raises(UnknownKeyError):
        assign_scheme(builder, "offical", [], dataset_dir=None)


def test_build_without_a_located_folder_hints_location(demo):
    (demo["raw"] / "PackDemo").rename(demo["raw"] / "Elsewhere")

    with pytest.raises(ConfigError) as info:
        build_dataset("packdemo", out=demo["pack"] / "packdemo")
    assert info.value.hint == "locate the dataset folder (see dfwb datasets info packdemo)"
    assert "PackDemo" in info.value.message
    assert not (demo["pack"] / "packdemo").exists()


def test_locate_metadata_root_uses_the_copy_holding_the_metadata(demo, monkeypatch, tmp_path):
    # A second root earlier in the list holds a copy of the folder without splits.json.
    early = tmp_path / "early"
    (early / "PackDemo" / "originals").mkdir(parents=True)
    (early / "PackDemo" / "originals" / "p00.mp4").touch()
    monkeypatch.setenv("DFWB_DATASETS_ROOT", os.pathsep.join([str(early), str(demo["raw"])]))
    builder = get_builder("packdemo")

    assert locate_metadata_root(builder) == demo["raw"] / "PackDemo"


def test_add_to_pack_yaml_keeps_the_list_sorted_and_is_idempotent(tmp_path):
    root = make_pack_root(tmp_path)
    assert add_to_pack_yaml(root, "zeta") is True
    assert add_to_pack_yaml(root, "alpha") is True
    assert add_to_pack_yaml(root, "zeta") is False
    data = yaml.safe_load((root / "pack.yaml").read_text("utf-8"))
    assert data == {
        "schema_version": 1,
        "name": "packdemo-pack",
        "version": "1.0.0",
        "datasets": ["alpha", "zeta"],
    }


def test_add_to_pack_yaml_without_a_pack_yaml_is_a_config_error(tmp_path):
    with pytest.raises(ConfigError) as info:
        add_to_pack_yaml(tmp_path, "packdemo")
    assert "pack.yaml" in info.value.message
    assert "new-pack" in info.value.hint


def test_add_to_pack_yaml_with_an_invalid_pack_yaml_is_a_contract_error(tmp_path):
    (tmp_path / "pack.yaml").write_text("schema_version: 1\nname: x\n", "utf-8")
    with pytest.raises(ContractError):
        add_to_pack_yaml(tmp_path, "packdemo")


def test_a_carve_dataset_without_pairs_or_benchmark(demo):
    build_inventory("packdemo-carve")
    out = demo["pack"] / "packdemo-carve"

    result = build_dataset("packdemo-carve", out=out)

    carve = result.schemes["official+ident-80-20"]
    assert (carve.rule, carve.params) == ("official+ident-80-20", {"policy": "official-train-test"})
    # 18 official train videos are carved into train and val; the 6 official val ones are left out.
    assert carve.counts is not None
    assert carve.counts["test"] == 6
    assert carve.counts.get("train", 0) + carve.counts.get("val", 0) == 18
    assert result.n_pairs == 0
    assert not (out / "pairs.jsonl.gz").exists()
    notice = (out / "NOTICE.md").read_text("utf-8")
    assert 'Paper: "A Synthetic Release" (Tests, 2026).' in notice
    assert "no homepage recorded" in notice


def test_a_benchmark_draws_from_every_record_when_the_official_split_has_no_test(demo):
    # The publisher labels val only: there is no official test to draw from, so the card says
    # the pool is every record, and recomputing the scheme needs no official split.
    inventory = build_inventory("packdemo-valonly").path
    records = read_inventory("packdemo-valonly", demo["work"])
    builder = get_builder("packdemo-valonly")

    result = build_dataset("packdemo-valonly", out=demo["pack"] / "packdemo-valonly")

    assert result.schemes["official"].counts == {"val": 6}
    benchmark = result.schemes["benchmark"]
    assert benchmark.params["pool"] == "all"
    rows = read_split_tsv(demo["pack"] / "packdemo-valonly" / "splits" / "benchmark.tsv.gz")
    expected = assign_benchmark(
        records,
        spec=builder.benchmark,
        is_real=builder.is_real,
        task_rank=builder.task_rank(),
        pool_keys=None,
    )
    assert {(r.key, r.compression) for r in rows} == set(expected)
    assert {local_key(r.key).partition("_")[0] for r in rows} - set(_OFFICIAL["test"])

    # As a recipe, it is recomputed from the inventory alone.
    add_to_pack_yaml(demo["pack"], "packdemo-valonly")
    (demo["pack"] / "packdemo-valonly" / "splits" / "benchmark.tsv.gz").unlink()
    assert needs_official("packdemo-valonly/benchmark") is False
    materialized = materialize(
        "packdemo-valonly/benchmark", inventory=inventory, official=None, work_root=demo["work"]
    )
    assert materialized.sha256 == benchmark.sha256


def _at_compressions(rows: Sequence[InventoryRecord], *names: str) -> list[InventoryRecord]:
    """Every row once per compression, as a dataset stored at several compressions is."""
    return [
        InventoryRecord(**{**_as_dict(r), "compression": name, "relpath": f"{name}/{r.relpath}"})
        for r in rows
        for name in names
    ]


def test_a_benchmark_defined_at_one_compression_ignores_the_others(demo, monkeypatch, tmp_path):
    # The same release with c40 and raw copies on disk as well draws exactly the benchmark an
    # inventory holding c23 alone draws; the card records the compression, and materializing
    # the recipe from the full inventory gives the published hash.
    monkeypatch.setattr(
        PackDemoBuilder, "benchmark", BenchmarkSpec(k_fake=2, compressions=("c23",))
    )
    rows = read_inventory("packdemo", demo["work"])
    only_c23, full = tmp_path / "c23.jsonl", tmp_path / "full.jsonl"
    write_jsonl(only_c23, _at_compressions(rows, "c23"))
    write_jsonl(full, _at_compressions(rows, "raw", "c23", "c40"))

    alone = build_dataset("packdemo", out=tmp_path / "alone" / "packdemo", inventory=only_c23)
    result = build_dataset("packdemo", out=demo["pack"] / "packdemo", inventory=full)

    benchmark = result.schemes["benchmark"]
    assert benchmark.params["compressions"] == ["c23"]
    assert benchmark.sha256 == alone.schemes["benchmark"].sha256
    assert benchmark.counts == {"test": 4}
    split = demo["pack"] / "packdemo" / "splits" / "benchmark.tsv.gz"
    assert {row.compression for row in read_split_tsv(split)} == {"c23"}

    add_to_pack_yaml(demo["pack"], "packdemo")
    split.unlink()
    records = read_jsonl(full, InventoryRecord)
    official = get_builder("packdemo").official_splits(demo["raw"] / "PackDemo", records)
    materialized = materialize(
        "packdemo/benchmark", inventory=full, official=official, work_root=demo["work"]
    )
    assert materialized.sha256 == benchmark.sha256


def test_a_dataset_without_an_official_scheme_needs_no_folder(demo):
    build_inventory("packdemo-noofficial")
    records = read_inventory("packdemo-noofficial", demo["work"])
    builder = get_builder("packdemo-noofficial")
    (demo["raw"] / "PackDemo").rename(demo["raw"] / "Elsewhere")

    assignment = assign_scheme(builder, "benchmark", records, dataset_dir=None)
    result = build_dataset("packdemo-noofficial", out=demo["pack"] / "packdemo-noofficial")

    assert result.schemes["benchmark"].params["pool"] == "all"
    assert result.schemes["benchmark"].counts == {"test": 4}
    assert len(assignment) == 4
    assert set(result.schemes) == {"ident-72-14-14", "benchmark"}


def test_a_stale_inventory_is_built_with_a_warning(demo, tmp_path, caplog):
    rows = read_inventory("packdemo", demo["work"])
    stale = tmp_path / "stale.jsonl"
    write_jsonl(
        stale,
        [InventoryRecord(**{**_as_dict(r), "builder": BuilderRef("packdemo", "0")}) for r in rows],
    )

    with caplog.at_level("WARNING", logger="dfwb.preprocess.packbuild"):
        build_dataset("packdemo", out=demo["pack"] / "packdemo", inventory=stale)

    assert "30 inventory row(s) were built by another version of the builder" in caplog.text


def test_output_inside_an_overridden_dataset_folder_is_refused(demo, monkeypatch, tmp_path):
    elsewhere = tmp_path / "elsewhere" / "PackDemo"
    elsewhere.parent.mkdir()
    (demo["raw"] / "PackDemo").rename(elsewhere)
    monkeypatch.setenv("DFWB_DATASET_PACKDEMO", str(elsewhere))

    with pytest.raises(ConfigError) as info:
        build_dataset("packdemo", out=elsewhere / "packdemo")
    assert "dataset folder" in info.value.message

    # The override is where the publisher's split is read from, too.
    assert locate_metadata_root(get_builder("packdemo")) == elsewhere


def test_add_to_pack_yaml_with_invalid_yaml_is_a_contract_error(tmp_path):
    (tmp_path / "pack.yaml").write_text("datasets: [\n", "utf-8")
    with pytest.raises(ContractError) as info:
        add_to_pack_yaml(tmp_path, "packdemo")
    assert "invalid YAML" in info.value.message


def _as_dict(record: InventoryRecord) -> dict[str, Any]:
    return {name: getattr(record, name) for name in record.__dataclass_fields__}
