"""A tiny two-task builder, a tree to run it on, and a fake plugin that registers it.

The builder is registered by import path (like any real builder), so ``get_builder`` goes through
the real registry: the target is imported only when a test builds it.
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping, Sequence
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest

from dfwb.core import plugins
from dfwb.core.records import BuilderRef, InventoryRecord
from dfwb.preprocess.inventory.base import BaseBuilder, LabelSpec, SchemeSpec, TaskSpec
from dfwb.protocols.rules import BenchmarkSpec

__all__ = [
    "DEMO_TARGET",
    "BadKeyBuilder",
    "DemoBuilder",
    "DuplicatingBuilder",
    "NotABuilder",
    "UnknownTaskBuilder",
    "install",
    "make_demo_tree",
]

_MODULE = "tests.unit.preprocess.inventory._demo"
DEMO_TARGET = f"{_MODULE}:DemoBuilder"


class DemoBuilder(BaseBuilder):
    """Reals under ``originals/<cX>/``; one face-swap method under ``swapped/<cX>/``.

    A fake is named ``<target>_<source>``: the target is its identity and its pairing group.
    """

    dataset_id = "demo"
    expected_folder = "Demo"
    label_prefix = "DEMO"
    tasks = (
        TaskSpec("REAL", "Originals", "real", "originals/{cX}", "original"),
        TaskSpec("FS_SWAP", "Swapper", "fake", "swapped/{cX}", "Swapper"),
    )
    known_compressions = ("c23", "c40")
    labels = {
        "REAL": LabelSpec(binary=0, binary_av=0, multiclass=0, family="real"),
        "FS_SWAP": LabelSpec(binary=1, binary_av=1, multiclass=1, family="face-swap"),
    }
    schemes = {
        "all-test": SchemeSpec("all-test", "subset", rationale="every video is test"),
        "benchmark": SchemeSpec("benchmark", "subset", rationale="a small balanced test set"),
    }
    default_scheme = "all-test"
    benchmark = BenchmarkSpec(k_fake=2)
    card_info = {
        "name": "Demo",
        "release": "1",
        "license": {"spdx": None, "summary": "synthetic test data"},
        "access": "generated by the tests",
        "modalities": ["video"],
        "compressions": ["c23", "c40"],
        "key_rule": "<task>/<file stem>",
    }
    layout_notes = "Fakes are named <target>_<source>."

    def record_for_video(
        self, task: TaskSpec, path: Path, relpath: str, compression: str | None
    ) -> InventoryRecord | None:
        stem = path.stem
        if task.kind == "real":
            return self.record(task, stem, relpath, compression, identity=stem, target_id=stem)
        target, _, source = stem.partition("_")
        if not source:
            return None  # a stray file in a fake directory
        return self.record(
            task,
            stem,
            relpath,
            compression,
            identity=target,
            target_id=target,
            source_id=source,
            pair_key=target,
        )


class DuplicatingBuilder(DemoBuilder):
    """Yields every record twice: a builder bug the runner must catch."""

    dataset_id = "dup"

    def discover(
        self, root: Path, *, compressions: Sequence[str] | None = None
    ) -> Iterator[InventoryRecord]:
        for record in super().discover(root, compressions=compressions):
            yield record
            yield record


def _raw_record(key: str) -> InventoryRecord:
    return InventoryRecord(
        key=key,
        compression=None,
        label_key="DEMO-REAL",
        method="original",
        relpath="originals/x.mp4",
        builder=BuilderRef("demo", "1"),
    )


class BadKeyBuilder(DemoBuilder):
    """Yields a key without a task prefix."""

    dataset_id = "badkey"

    def discover(
        self, root: Path, *, compressions: Sequence[str] | None = None
    ) -> Iterator[InventoryRecord]:
        yield _raw_record("no-slash")


class UnknownTaskBuilder(DemoBuilder):
    """Yields a key whose task is not in the task table."""

    dataset_id = "unknowntask"

    def discover(
        self, root: Path, *, compressions: Sequence[str] | None = None
    ) -> Iterator[InventoryRecord]:
        yield _raw_record("NOPE/x")


class NotABuilder:
    """Registered as an inventory builder by mistake: it does not subclass the base."""


def make_demo_tree(
    root: Path,
    *,
    reals: Iterable[str] = ("000", "001"),
    fakes: Iterable[str] = ("000_001", "001_000"),
    compressions: Iterable[str] = ("c23", "c40"),
) -> Path:
    """Touch a Demo release under ``root``: every real and fake in every compression."""
    reals, fakes = list(reals), list(fakes)
    for compression in compressions:
        for directory, stems in (("originals", reals), ("swapped", fakes)):
            folder = root / directory / compression
            folder.mkdir(parents=True, exist_ok=True)
            for stem in stems:
                (folder / f"{stem}.mp4").touch()
    return root


class _EntryPoint:
    """Duck-typed stand-in for ``importlib.metadata.EntryPoint``."""

    name = "demo-plugin"
    value = "fake_demo_plugin:register"
    group = plugins.ENTRY_POINT_GROUP
    dist = SimpleNamespace(name="demo-plugin", version="0.0.0")

    def __init__(self, register: Any) -> None:
        self._register = register

    def load(self) -> Any:
        return self._register


def install(
    monkeypatch: pytest.MonkeyPatch,
    builders: Mapping[str, tuple[str, str, str]] | None = None,
    *,
    packs: Mapping[str, Path] | None = None,
) -> None:
    """Replace every plugin with one fake plugin that registers ``builders`` and ``packs``.

    ``builders`` maps a dataset id to ``(target, display name, expected folder)``; the default
    registers :class:`DemoBuilder` as ``demo``. ``packs`` maps a pack name to a pack root as
    written by ``tests.unit.protocols.conftest.make_pack``.
    """
    builders = {"demo": (DEMO_TARGET, "Demo", "Demo")} if builders is None else builders
    packs = packs or {}
    for path in packs.values():
        monkeypatch.syspath_prepend(str(path.parent.parent))

    def register(api: Any) -> None:
        for dataset_id, (target, name, folder) in builders.items():
            api.inventory_builders.add(dataset_id, target=target, summary=name, folder=folder)
        for name, path in packs.items():
            api.protocol_packs.add(
                name, target=f"{path.parent.name}:{path.name}", summary=f"fixture pack {name!r}"
            )

    entry_point = _EntryPoint(register)
    monkeypatch.setattr(
        plugins,
        "_entry_points",
        lambda group: [entry_point] if group == plugins.ENTRY_POINT_GROUP else [],
    )
